[build]
command = "wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.6-stable.tar.xz &&
           tar xf flutter_linux_3.13.6-stable.tar.xz &&
           export PATH=$PATH:`pwd`/flutter/bin &&
           flutter doctor &&
           flutter build web"
publish = "build/web"